version: "3.7"

services:
  sqldb:
    image: mysql:8
    container_name: sqldb
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      devops-app:

  vernemq:
    container_name: vernemq
    image: vernemq/vernemq
    ports:
      - "${MQTT_WSS_PORT}:8080"
      - "${MQTT_MQTT_PORT}:1883"
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_LISTENER.tcp.allowed_protocol_versions=3,4,5
      - DOCKER_VERNEMQ_LISTENER.ws.allowed_protocol_versions=3,4,5
      - DOCKER_VERNEMQ_LISTENER.wss.allowed_protocol_versions=3,4,5
    volumes:
      - vernemq-data:/vernemq/data
    networks:
      devops-app:

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - ${ADMINER_HOST_PORT}:8080
    networks:
      devops-app:

networks:
  devops-app:
    name: devops-app

volumes:
  mysql-data:
  vernemq-data:
